name: 部署文档

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-adc:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18'
      PNPM_VERSION: '8'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}


      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建文档
        run: pnpm run docs:build

      - name: 部署文档
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: ytuoxx/ytuoxx.github.io 
          target_branch: main
          build_dir: src/.vuepress/dist
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}